### ISSUE TITLE
remove `No-Self loop allowed` restriction

### ISSUE THREAD

**Issue by j-i-k-o** [OpenJij/cimod#48]
duplicate index such that `quadratic={(2,2): 5}` should be dealt with:
* in the case of `SPIN`:
`linear={} quadratic={} offset=5`
* in the case of `BINARY`:
`linear={2:5} quadratic={} offset=0`

**Comment by K-Suzuki-Jij** [comment]
This issue still remains for the BinaryQuadraticModel.

```
import cimod
cimod.BinaryQuadraticModel({}, {(2,2):5}, "SPIN")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/cimod/model/binary_quadratic_model.py", line 324, in BinaryQuadraticModel
    return Model(linear, quadratic, offset, vartype)
  File "/usr/local/lib/python3.9/site-packages/cimod/model/binary_quadratic_model.py", line 158, in __init__
    mat, idx_to_label = self._generate_mat(
  File "/usr/local/lib/python3.9/site-packages/cimod/model/binary_quadratic_model.py", line 175, in _generate_mat
    raise RuntimeError("No self-loop allowed")
RuntimeError: No self-loop allowed
```

**Comment by 29rou** [comment]
```sh 
quadratic : {(2, 2): 5}
include_quaddiag : False
linear : {}
<ExceptionInfo RuntimeError('No self-loop allowed') tblen=4>
```

**Comment by durga0201** [comment]
To resolve this issue, you need to remove or handle self-loops in your quadratic dictionary. Here's an example of how you might modify your code to check for and remove self-loops:

```
>>> import cimod
>>> linear = {}
>>> quadratic = {(2, 3): 5,(2,2):5}
>>> quadratic_no_self_loops = {key: value for key, value in quadratic.items() if key[0] != key[1]}
>>> bqm = cimod.BinaryQuadraticModel(linear, quadratic_no_self_loops, "SPIN")
>>> print(bqm)
BinaryQuadraticModel({}, {(2, 3): 5.0}, 0.0, Vartype.SPIN, sparse=False)
```

I guess this should close the issue.

**Comment by durga0201** [comment]
@29rou can I take up this case?

**Comment by j-i-k-o** [comment]
This PR should be closed due to the following reasons.
* Even if `No self-loop allowed` error occurs in `BinaryQuadraticModel`, this can be avoided by the following:
   - Remove self-loop case as @durga0201 suggested.
   - Use `linear` keyword such as 
 ```python
>>> linear = {2: 5}
>>> quadratic = {(2, 3): 5}
```
I'll add this feature to the `README.md` as a specification.

**Comment by 29rou** [comment]
I'm so grateful for your thoughtful response to the issue.
