### ISSUE TITLE
Add env variable to not download dependencies

### ISSUE THREAD

**Issue by BastianZim** [OpenJij/cimod#76]
Hi,

this is in the process of me adding this package to conda-forge since it is a Dimod dependency.

Would it be possible to add an env variable that prevents the dependencies from being downloaded and instead fails the build process, if the dependencies aren't already available in the host system?
Just something simple like _try to find dependencies locally -> if not, fail with error message about missing dependency_

Reason is that conda-forge prefers to use its own packages so I could be certain that I didn't miss anything and something is downloaded.

Ref: 
1. https://github.com/conda-forge/staged-recipes/pull/19094
2. Example: https://github.com/OpenJij/cimod/blob/0d8832146ee640835ac7dd7e2b643313a9016e3f/external/eigen.cmake#L4-L9

**Comment by BastianZim** [comment]
Oh that looks great!

All of them would be perfect. Basically, during compilation nothing external should be downloaded if I set an environment variable, and only already available packages should be used. 

Then, I can download them using condas's mechanism and make them available to the build tool. 

On a slightly related note: Why are some of them already packaged? Are they modified or what is the reason?

**Comment by j-i-k-o** [comment]
Thanks for the feedback!

I would like to consolidate your request first.
Is your request to define an environment variable that gives us an error when the external package (e.g. Eigen, BLAS, etc...) is not on the local environment if it is enabled?

Many thanks.

**Comment by BastianZim** [comment]
Yes, that would be the idea. 
Most of the stuff is already defined in the pyproject.toml but for the other dependencies outside of it (everything in _cimod/external_) the workflow is currently:

```mermaid
flowchart TD
  Build -->|Dependency available | Use
  Build -->|Dependency not available| Install
```

Instead it would be great to have:

```mermaid
flowchart TD
  Build -->|Dependency available | Use
  Build -->|Dependency not available and env variable not set| Install
Build -->|Dependency not available and env variable set| Fail
```

**Comment by BastianZim** [comment]
Edit: Seems like mermaid rendering is not correctly working but it should look like this:

**Currently:**
Build -> Dependency available -> Use
Build -> Dependency not available -> Install

**New version:**
Build -> Dependency available -> Use
Build -> Dependency not available and env variable not set -> Install
Build -> Dependency not available and env variable set -> Fail

**Comment by BastianZim** [comment]
This tool pretty much does the same thing: https://github.com/google/or-tools/blob/49b6301e1e1e231d654d79b6032e79809868a70e/cmake/python.cmake#L71

**Comment by 29rou** [comment]
Thank you. I will try to implement it.

**Comment by BastianZim** [comment]
Thank you! Unfortunately I don't know any C++ but happy to help with anything where I can. :)

**Comment by 29rou** [comment]
According to the CMake documentation, with this variable set, the package will be REQUIRED and the build will fail if the package is not found.
https://github.com/OpenJij/cimod/blob/a477c10f99ccbccb3782054bb80041bd6086da0c/CMakeLists.txt#L56-L60

**Comment by BastianZim** [comment]
Ahh perfect! Then that's exactly what I needed. Thank you!

**Comment by BastianZim** [comment]
Actually, I thought this is already implemented since it's in CMAKE but should I still leave the issue open?

**Comment by 29rou** [comment]
No worries.  If You can work well this CMake, You should close this issue.

**Comment by BastianZim** [comment]
Actually, just realised one thing: This command only works if I know which packages are being used. In case you introduce some new ones at some point you'd need to only include them in one location so that I know where to look. Do you think that will be the case?
Otherwise some sort of catch-all would be great.

**Comment by 29rou** [comment]
How about this?

**Comment by BastianZim** [comment]
That’s perfect, thank you!
